# This file is ONLY for local testing.
# On Streamlit Cloud, set secrets in the web UI (App > Settings > Secrets).
MODEL_URL = "https://drive.google.com/uc?id=YOUR_FILE_ID"
CLASS_NAMES = "Healthy,Diseased"
IMG_SIZE = "224,224"
